# Define some colors
COLORS = {
    'RED': (255, 0, 0),
    'GREEN': (0, 255, 0),
    'BLUE': (0, 0, 255),
    'YELLOW': (255, 255, 0),
    'MAGENTA': (255, 0, 255),
    'CYAN': (0, 255, 255)
}

PYRAMID_VERTICES = [
    [-1, -1, 0],  # 0
    [1, -1, 0],  # 1
    [1, 1, 0],    # 2
    [-1, 1, 0],  # 3
    [0, 0, 2]     # 4
]

PYRAMID_FACES = [
    [PYRAMID_VERTICES[0], PYRAMID_VERTICES[1], PYRAMID_VERTICES[2], PYRAMID_VERTICES[3], COLORS['RED']], 
    [PYRAMID_VERTICES[0], PYRAMID_VERTICES[1], PYRAMID_VERTICES[4], COLORS['GREEN']], 
    [PYRAMID_VERTICES[1], PYRAMID_VERTICES[2], PYRAMID_VERTICES[4], COLORS['BLUE']], 
    [PYRAMID_VERTICES[2], PYRAMID_VERTICES[3], PYRAMID_VERTICES[4], COLORS['YELLOW']], 
    [PYRAMID_VERTICES[3], PYRAMID_VERTICES[0], PYRAMID_VERTICES[4], COLORS['MAGENTA']]
]

CUBE_VERTICES = [
    [-1, -1, -1],
    [1, -1, -1],
    [1, 1, -1],
    [-1, 1, -1],
    [-1, -1, 1],
    [1, -1, 1],
    [1, 1, 1],
    [-1, 1, 1]
]

CUBE_FACES = [
    [CUBE_VERTICES[0], CUBE_VERTICES[1], CUBE_VERTICES[2], CUBE_VERTICES[3], COLORS['RED']],
    [CUBE_VERTICES[4], CUBE_VERTICES[5], CUBE_VERTICES[6], CUBE_VERTICES[7], COLORS['GREEN']],
    [CUBE_VERTICES[0], CUBE_VERTICES[1], CUBE_VERTICES[5], CUBE_VERTICES[4], COLORS['BLUE']],
    [CUBE_VERTICES[1], CUBE_VERTICES[2], CUBE_VERTICES[6], CUBE_VERTICES[5], COLORS['YELLOW']],
    [CUBE_VERTICES[2], CUBE_VERTICES[3], CUBE_VERTICES[7], CUBE_VERTICES[6], COLORS['MAGENTA']],
    [CUBE_VERTICES[0], CUBE_VERTICES[3], CUBE_VERTICES[7], CUBE_VERTICES[4], COLORS['CYAN']]
]

# Shapes
PYRAMID = (PYRAMID_VERTICES, PYRAMID_FACES)
CUBE = (CUBE_VERTICES, CUBE_FACES)